shutdown_costmaps: false

controller_frequency: 0
controller_patience: 15.0

planner_frequency: 20.0
planner_patience: 5.0

oscillation_timeout: 0.0
oscillation_distance: 0.5

recovery_behavior_enabled: false
clearing_rotation_allowed: false

use_global_costmap: false
use_local_costmap: false